name: Afrikana Exotic Foods
favicon: null
layout_spectrum: 0.97572
typography_spectrum: 0.8157575766090304
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#df2516'
    - '#eb765a'
    - '#7b7c77'
  brandStrength: 0.3915449462365359
  lightness: 0.8475093189626932
  saturation: 0.5435881004668772
  rhythmicContrast: 0.057232026709243655
purpose: []
